import React from 'react'
import Document, { Head, Html, Main, NextScript } from 'next/document';
 class MyDocument extends Document{
     static async getInitialProps (ctx) {
         const initialProps = await Document.getInitialProps()
         return{ ...initialProps}
     }

     render() {
         return (
             <Html>
                <Head>
                <title>Tecblic</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.png" />                
                </Head>
                 <body>
                     <Main/>
                     <NextScript/>
                 </body>
             </Html>
         )
     }
 }

 export default Document;