import Head from 'next/head'
import Footer from '../components/Footer';
import NavBar from '../components/NavBar'
import styles from '../styles/Home.module.css'
import HomePage from './home/HomePage';
export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Tecblic</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/assets/img/logo.png" />
      </Head>
      <NavBar/>
      <HomePage/>
      <Footer/>
     
    </div>
  )
}
